services:
  clock:
    build: .
    container_name: zegar
    environment:
      - DISPLAY=:0
      - TZ=${TZ:-Europe/Warsaw}
      - XAUTHORITY=/root/.Xauthority
    volumes:
      # XWayland socket
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Xauthority – klucz dostępu do XWayland
      - /home/pnt/.Xauthority:/root/.Xauthority:ro
      # Konfiguracja alarmu
      - ./.env:/app/.env
    network_mode: host
    restart: unless-stopped
